/** @type {import('tailwindcss').Config} */
export default {
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "on-secondary-container": "#fff6f0",
                "tertiary-fixed": "#ff9289",
                "tertiary-container": "#fe4e49",
                "on-surface": "#ffffff",
                "surface-tint": "#8bacff",
                "inverse-on-surface": "#565555",
                "on-tertiary": "#4a0004",
                "primary-dim": "#036cfb",
                "on-primary": "#002a6c",
                "on-primary-fixed": "#000000",
                "surface-dim": "#0e0e0e",
                "secondary-fixed-dim": "#ffb55b",
                "outline-variant": "#484847",
                "on-error-container": "#ffa8a3",
                "secondary": "#fc9e00",
                "inverse-primary": "#0057cf",
                "surface-container-high": "#20201f",
                "surface-container-low": "#131313",
                "primary-fixed": "#759eff",
                "on-primary-container": "#001f55",
                "on-secondary-fixed": "#4d2d00",
                "surface-bright": "#2c2c2c",
                "secondary-dim": "#e99200",
                "on-secondary-fixed-variant": "#744600",
                "tertiary-dim": "#ff7168",
                "surface-variant": "#262626",
                "error-container": "#9f0519",
                "primary-container": "#759eff",
                "error": "#ff716c",
                "surface-container-highest": "#262626",
                "on-surface-variant": "#adaaaa",
                "on-secondary": "#4b2c00",
                "surface-container-lowest": "#000000",
                "background": "#0e0e0e",
                "surface": "#0e0e0e",
                "tertiary-fixed-dim": "#ff7b71",
                "on-error": "#490006",
                "secondary-container": "#875200",
                "secondary-fixed": "#ffc789",
                "on-tertiary-fixed": "#3a0002",
                "error-dim": "#d7383b",
                "on-tertiary-container": "#1f0001",
                "surface-container": "#1a1a1a",
                "outline": "#767575",
                "on-background": "#ffffff",
                "inverse-surface": "#fcf9f8",
                "primary-fixed-dim": "#5d8fff",
                "primary": "#8bacff",
                "on-primary-fixed-variant": "#002868",
                "tertiary": "#ff7168",
                "on-tertiary-fixed-variant": "#7a000b"
            },
            fontFamily: {
                "headline": ["Space Grotesk"],
                "body": ["Inter"],
                "label": ["Space Grotesk"]
            },
            borderRadius: {"DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px"},
        },
    },
    plugins: [],
}
